### ISSUE TITLE
now we have an issue

### ISSUE THREAD

**Issue by Junior2Ran** [huiyan-fe/vis-ui#1]

**Comment by zmofei** [comment]
which issue?

**Comment by Junior2Ran** [comment]
@zmofei 
It is just a test for [quality badge](http://packagequality.com/#?package=vis-ui). The quality algorithm is related to the number of issues.

You can try it on your repos too. 😄

**Comment by Junior2Ran** [comment]
now I am going to close this issue, and then the quality score will be up to nearly 80 as expect.
